### ISSUE TITLE
Meta issue

### ISSUE THREAD

**Issue by fabiommendes** [pydemic/capacidade_hospitalar#1]
# Prioridade 0

- [x] Aplicar tema do Material Frontend nas URLS do allauth
- [x] Criar modelo de Profile ou modificar user c/ CPF e nome complet, UF e campo que diz que usuário está validado ou não
- [x] Incluir CPF obrigatório (e validado) e UF no formulário de cadastro (usar algum app django que faça isso)
- [x] Exigir nome no cadastro de usuários
- [x] Configurar e-mail e re-habilitar confirmação do cadastro no e-mail
- [x] Criar migração para incluir a base do CNES no banco

# Prioridade 1
- [ ] **NENHUM** erro de N+1 no banco
- [x] Trocar o select de município para um auto complete
- [ ] Destacar linhas no informe diário separando adulto vs pediatrico

# Prioridade 2
- [ ] Expor API (REST?)
- [ ] Cache na API
- [ ] Pré-preencher notificação diária com casos do dia anterior 

# Prioridade 3
- [ ] Sistema de notificação que lembre o usuário de preencher diariamente o cadastro (manda um e-mail, depois um zap ou telegram)

**Comment by fabiommendes** [comment]
Fechei uma issue porque os requisitos já mudaram ;)

**Comment by fabiommendes** [comment]
Mais issues, depois distribuímos
* [ ] Colocar CAPTCHA em cadastro

**Comment by fabiommendes** [comment]
# Regras de negócio

Existem alguns usuários:
* site admin: (django normal)
* gestor estadual: valida os usuários notificadores associados a um estado específico
* usuário notificador (usuários normais)

**Comment by fabiommendes** [comment]
# Infra

1. Criar tasks para preencher o banco com informações. Pode ser no inv (+1) ou comando django (-1)
2. Fazer testes de carga
3. Fazer testes!
4. Fazer testes!
5. Fazer testes para bugs N+1
